export const products = [
    {
        id: 1,
        name: "iPhone 11 Pro 256GB Memory",
        image: "/images/iphone.jpg",
        description:
            "Shoot 4K video, beautiful portraits and sweeping landscapes with the all-new dual-camera system. Capture your best low-light photos with Night mode. See true-to-life colour in your photos, videos and games on the 6.1-inch Liquid Retina display.3 Experience unprecedented performance with A13 Bionic for gaming, augmented reality and photography",
        brand: "Apple",
        category: "Electronics",
        price: 929.99,
        rating: 1,
        numReviews: 0,
        isNew: true,
        reviews: [],
        stock: 5,
    },
    {
        id: 2,
        name: "Samsung Galaxy Tab S6",
        image: "/images/tab.jpg",
        description:
            "Galaxy Tab S6 Lite is your super carriable note-taking, go-getting companion. It comes with a large 10.4 inch display on a slim and light build, One UI 4 on Android, and S Pen in box and ready to go. Whether you're drawing, learning or gaming, this is the tablet made to be in the moment.",
        brand: "Sony",
        category: "Electronics",
        price: 399.99,
        countInStock: 11,
        rating: 5,
        numReviews: 0,
        isNew: false,
        reviews: [],
        stock: 0,
    },
    {
        id: 3,
        name: "Samsung Galaxy Watch5 Pro",
        image: "/images/s4prowatch.jpg",
        description:
            "Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience",
        brand: "Logitech",
        category: "Electronics",
        price: 299.99,
        rating: 1,
        numReviews: 0,
        isNew: false,
        reviews: [],
        stock: 7,
    },
    {
        id: 5,
        name: "Samsung Galaxy S4 Watch",
        image: "/images/s4watch.jpg",
        description:
            "Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space",
        brand: "Amazon",
        category: "Electronics",
        price: 299.99,
        rating: 4,
        numReviews: 1,
        isNew: false,
        reviews: [],
        stock: 1,
    },
];
